# Generated by Django 5.2.4 on 2025-08-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='comment',
            new_name='comment_department',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='score_department',
        ),
        migrations.AddField(
            model_name='rating',
            name='comment_doctor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='comment_hospital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='score_doctor',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='score_hospital',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
