# Generated by Django 5.2.4 on 2025-08-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rename_comment_rating_comment_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment_department',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment_doctor',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment_hospital',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='department',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score_department',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score_doctor',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score_hospital',
        ),
        migrations.CreateModel(
            name='RatingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('doctor', 'Doctor'), ('hospital', 'Hospital'), ('department', 'Department')], max_length=20)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ratings.rating')),
            ],
        ),
    ]
