# Generated by Django 5.2.6 on 2025-09-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_user_date_joined'),
        ('hospitals', '0009_alter_hospital_latitude_alter_hospital_longitude'),
        ('ratings', '0004_alter_rating_options_remove_rating_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='doctor',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='doc_ratings', to='accounts.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='hospital',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_ratings', to='hospitals.hospital'),
            preserve_default=False,
        ),
    ]
