# Generated by Django 5.2.6 on 2025-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_user_serial_number_user__serial_number_and_more'),
        ('hospitals', '0010_alter_service_name'),
        ('ratings', '0005_rating_doctor_rating_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='appointment_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('appointment_id', 'doctor', 'hospital')},
        ),
    ]
