# Generated by Django 5.2.4 on 2025-08-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('cardiology', 'Кардиологија'), ('neurology', 'Неврологија'), ('pediatrics', 'Педијатрија'), ('orthopedics', 'Ортопедија'), ('psychiatry', 'Психијатрија')], max_length=50),
        ),
    ]
