# Generated by Django 5.2.4 on 2025-08-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_blacklisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='approved',
            new_name='authorized',
        ),
    ]
