# Generated by Django 5.2.4 on 2025-08-28 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_approved_doctor_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 17, 22, 39, 634227, tzinfo=datetime.timezone.utc)),
        ),
    ]
