# Generated by Django 5.2.4 on 2025-08-28 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 19, 45, 1, 552469, tzinfo=datetime.timezone.utc)),
        ),
    ]
