# Generated by Django 5.2.4 on 2025-08-28 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 28, 20, 7, 25, 582490, tzinfo=datetime.timezone.utc)),
        ),
    ]
