# Generated by Django 5.2.4 on 2025-08-30 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_date_joined_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 9, 53, 10, 177319, tzinfo=datetime.timezone.utc)),
        ),
    ]
