# Generated by Django 5.2.4 on 2025-08-30 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 10, 13, 18, 279722, tzinfo=datetime.timezone.utc)),
        ),
    ]
