# Generated by Django 5.2.4 on 2025-09-02 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 17, 57, 30, 387623, tzinfo=datetime.timezone.utc)),
        ),
    ]
