# Generated by Django 5.2.4 on 2025-09-02 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 19, 1, 41, 105829, tzinfo=datetime.timezone.utc)),
        ),
    ]
