# Generated by Django 5.2.4 on 2025-09-03 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 18, 2, 42, 158310, tzinfo=datetime.timezone.utc)),
        ),
    ]
