# Generated by Django 5.2.4 on 2025-09-05 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 12, 52, 55, 285491, tzinfo=datetime.timezone.utc)),
        ),
    ]
