# Generated by Django 5.2.4 on 2025-09-05 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 18, 43, 51, 780618, tzinfo=datetime.timezone.utc)),
        ),
    ]
