# Generated by Django 5.2.6 on 2025-09-18 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 17, 40, 51, 578175, tzinfo=datetime.timezone.utc)),
        ),
    ]
