# Generated by Django 5.2.6 on 2025-09-20 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_share_info_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 20, 48, 58, 561960, tzinfo=datetime.timezone.utc)),
        ),
    ]
