# Generated by Django 5.2.6 on 2025-09-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='user',
            name='_serial_number',
            field=models.TextField(db_column='serial_number', default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('cardiology', 'Кардиологија'), ('neurology', 'Неврологија'), ('pediatrics', 'Педијатрија'), ('orthopedics', 'Ортопедија'), ('psychiatry', 'Психијатрија'), ('otorhinolaryngology', 'Оториноларингологија')], max_length=50),
        ),
    ]
