# Generated by Django 5.2.6 on 2025-09-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_user_serial_number_user__serial_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneVerification',
            new_name='MailVerification',
        ),
    ]
