# Generated by Django 5.2.4 on 2025-09-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
