# Generated by Django 5.2.6 on 2025-09-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_share_info_alter_user_date_joined'),
        ('appointments', '0004_alter_appointment_patient_alter_appointment_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_comments', to='accounts.doctor')),
            ],
        ),
    ]
