# Generated by Django 5.2.6 on 2025-09-20 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointmentcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='appointmentcomment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointmentcomment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentcomment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentcomment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_comments_from_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
