# Generated by Django 5.2.6 on 2025-09-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointmentcomment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_reccuring',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reccurence_pattern',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
