# Generated by Django 5.2.4 on 2025-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_department_doctordepartmentassignment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_qrcodes/'),
        ),
    ]
