# Generated by Django 5.2.4 on 2025-08-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='hospital',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
