# Generated by Django 5.2.4 on 2025-08-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_approved_doctor_authorized'),
        ('hospitals', '0004_remove_hospital_qr_code_hospital_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_services', to='accounts.doctor')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_doctors', to='hospitals.service')),
            ],
            options={
                'verbose_name': 'Doctor Service Assignment',
                'verbose_name_plural': 'Doctor Service Assignments',
            },
        ),
        migrations.DeleteModel(
            name='DoctorService',
        ),
        migrations.AddConstraint(
            model_name='doctorserviceassignment',
            constraint=models.UniqueConstraint(fields=('doctor', 'service'), name='unique_doctor_service'),
        ),
    ]
