# Generated by Django 5.2.4 on 2025-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_doctorserviceassignment_delete_doctorservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='town',
            field=models.CharField(default='NON', max_length=30),
        ),
    ]
